services:
  postgres:
    image: postgres:latest
    container_name: postgres-mvp-dev
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 281004
      POSTGRES_DB: mvp-dev
    volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data:
    driver: local